### ISSUE TITLE
heroku CI: compilation during "test setup" and "test" fase

### ISSUE THREAD

**Issue by twiggler** [heroku/heroku-buildpack-gradle#80] opened 2020-10-29 14:45 UTC
Hi there,

We are using heroku-buildpack-gradle with kotlin. 

During a ci test run, I see that everything is compiled twice, both during the test-setup and test phase 

![image](https://user-images.githubusercontent.com/12800443/97589109-7547eb80-19fd-11eb-936f-9844bf10e81d.png)

When specifying a custom "dummy" gradle task for the test-setup fase, it runs 2.5 mins faster.

While reading the bash scripts, I got the impression that build artefacts should be cached between phases.

Any tips?

**Comment by Malax** [comment] 2020-11-16 10:06
Hey @twiggler,

sorry for the long delay on the issue. I'll take a look and see if we can fix this soon. Thanks for the report!

**Comment by Malax** [comment] 2020-11-16 12:33
@twiggler I can't reproduce the issue on my end, do you have a public repository handy where this issue occurs?

**Comment by twiggler** [comment] 2020-11-19 10:43
@Malax Thank you for getting back to me!

I setup and make a public repository in the weekend.

**Comment by twiggler** [comment] 2020-11-21 10:31
Hey @Malax,

I [forked ](https://github.com/twiggler/javalin-kotlin-gradle-heroku ) an example kotlin - javalin project which exhibits the same behavior, i.e. recompilation during test execution.

![image](https://user-images.githubusercontent.com/12800443/99875073-138a3400-2bed-11eb-87fa-9908832d944d.png)

**Comment by Malax** [comment] 2020-11-24 08:00
Thank you @twiggler, appreciated! I'll look into this and will update this issue.

**Comment by Malax** [comment] 2020-11-26 08:55
@twiggler A fix will be merged soon via #82 and deployed next week. I'll update this issue after the deploy, after which you can remove your workaround.

**Closed** 2020-11-26 08:58 UTC

**Comment by twiggler** [comment] 2020-11-26 09:35
@Malax Thank you very much!

**Comment by Malax** [comment] 2020-12-01 14:02
Released as `v33` via #83 - Thanks again for the report @twiggler!
